do $$
begin
  if not exists (select 1 from pg_type where typname = 'event_status' and typnamespace = 'public'::regnamespace) then
    create type public.event_status as enum ('IN_REVIEW', 'PUBLISHED', 'REJECTED', 'CANCELLED', 'DONE');
  end if;
end $$;

create table if not exists public.event (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  organizer_id bigint not null references public."user" (user_id) on update cascade on delete cascade,
  title text not null,
  description text not null,
  start_time timestamptz not null,
  end_time timestamptz,
  address_id bigint references public.address (id) on update cascade on delete set null,
  place_name text,
  price double precision not null default 0 check (price >= 0),
  capacity integer check (capacity is null or capacity > 0),
  photo text,
  photo_credit text,
  status public.event_status not null default 'IN_REVIEW',
  review_note text,
  reviewed_by bigint references public."user" (user_id) on update cascade on delete set null,
  reviewed_at timestamptz,
  constraint event_fim_depois_do_inicio check (end_time is null or end_time > start_time)
);

create index if not exists event_status_inicio_idx on public.event (status, start_time);
create index if not exists event_organizer_idx on public.event (organizer_id);

create table if not exists public.event_attendance (
  event_id bigint not null references public.event (id) on update cascade on delete cascade,
  user_id bigint not null references public."user" (user_id) on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create index if not exists event_attendance_user_idx on public.event_attendance (user_id);

alter table public.event enable row level security;
alter table public.event_attendance enable row level security;
