create table if not exists public."user" (
  user_id bigint generated by default as identity primary key,
  username text not null unique,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  password text not null,
  phone text not null,
  role text not null,
  photo text not null default '',
  cnpj text,
  created_at timestamptz not null default now()
);

create table if not exists public.address (
  id bigint generated by default as identity primary key,
  cep text not null,
  uf text not null,
  city text not null,
  neighborhood text not null,
  street text not null,
  number text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tour (
  id bigint generated by default as identity primary key,
  created_by_id bigint not null references public."user" (user_id),
  title text not null,
  description text,
  price numeric(10, 2) not null,
  estimated_duration_minutes integer not null,
  meeting_point text not null,
  photo text not null,
  address_id bigint not null references public.address (id),
  created_at timestamptz not null default now()
);

create table if not exists public.tour_instance (
  id bigint generated by default as identity primary key,
  tour_id bigint not null references public.tour (id),
  start_time timestamptz not null,
  max_capacity integer not null,
  status text not null default 'SCHEDULED',
  created_at timestamptz not null default now()
);

create table if not exists public.tour_request (
  id bigint generated by default as identity primary key,
  tour_instance_id bigint not null references public.tour_instance (id),
  requester_id bigint not null references public."user" (user_id),
  status text not null default 'PENDING',
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.chat (
  id bigint generated by default as identity primary key,
  tour_instance_id bigint not null unique references public.tour_instance (id),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_message (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chat (id),
  user_id bigint not null references public."user" (user_id),
  text text not null,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_proc where proname = 'get_tour_members') then
    create function public.get_tour_members(tour_instance_id bigint)
    returns table (user_id bigint, first_name text, last_name text, photo text, role text)
    language sql stable as $body$
      select u.user_id, u.first_name, u.last_name, u.photo, u.role
      from public.tour_instance ti
      join public.tour t on t.id = ti.tour_id
      join public."user" u on u.user_id = t.created_by_id
      where ti.id = get_tour_members.tour_instance_id
      union
      select u.user_id, u.first_name, u.last_name, u.photo, u.role
      from public.tour_request tr
      join public."user" u on u.user_id = tr.requester_id
      where tr.tour_instance_id = get_tour_members.tour_instance_id and tr.status = 'ACCEPTED'
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_popular_tours') then
    create function public.get_popular_tours()
    returns table (id bigint, title text, photo text, guide text, guidephoto text, qt_turistas bigint)
    language sql stable as $body$
      select t.id, t.title, t.photo, u.first_name, u.photo, count(tr.id)
      from public.tour t
      join public."user" u on u.user_id = t.created_by_id
      left join public.tour_instance ti on ti.tour_id = t.id
      left join public.tour_request tr on tr.tour_instance_id = ti.id and tr.status = 'ACCEPTED'
      group by t.id, u.user_id
      order by count(tr.id) desc, t.created_at desc
      limit 20
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_tours_guide') then
    create function public.get_tours_guide(guide_id bigint)
    returns table (tour_id bigint, tour_instance_id bigint, tour_title text, tour_photo text, start_time timestamptz, chat_id bigint)
    language sql stable as $body$
      select t.id, ti.id, t.title, t.photo, ti.start_time, c.id
      from public.tour t
      join public.tour_instance ti on ti.tour_id = t.id
      left join public.chat c on c.tour_instance_id = ti.id
      where t.created_by_id = get_tours_guide.guide_id
        and exists (
          select 1 from public.tour_request tr
          where tr.tour_instance_id = ti.id and tr.status = 'ACCEPTED'
        )
      order by ti.start_time
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_tours_tourist') then
    create function public.get_tours_tourist(tourist_id bigint)
    returns table (tour_id bigint, tour_instance_id bigint, tour_title text, tour_photo text, start_time timestamptz, chat_id bigint)
    language sql stable as $body$
      select t.id, ti.id, t.title, t.photo, ti.start_time, c.id
      from public.tour_request tr
      join public.tour_instance ti on ti.id = tr.tour_instance_id
      join public.tour t on t.id = ti.tour_id
      left join public.chat c on c.tour_instance_id = ti.id
      where tr.requester_id = get_tours_tourist.tourist_id and tr.status = 'ACCEPTED'
      order by ti.start_time
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_tour_by_chat') then
    create function public.get_tour_by_chat(chat_id bigint)
    returns table (tour_id bigint, tour_instance_id bigint, tour_title text)
    language sql stable as $body$
      select t.id, ti.id, t.title
      from public.chat c
      join public.tour_instance ti on ti.id = c.tour_instance_id
      join public.tour t on t.id = ti.tour_id
      where c.id = get_tour_by_chat.chat_id
    $body$;
  end if;
end $$;
