create table if not exists public.password_reset (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint not null references public."user" (user_id) on update cascade on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz
);

create index if not exists password_reset_user_id_idx on public.password_reset (user_id);

alter table public.password_reset enable row level security;
