create table if not exists public.notification (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint not null references public."user" (user_id) on update cascade on delete cascade,
  kind text not null,
  title text not null,
  body text,
  link text,
  read_at timestamptz
);

create index if not exists notification_user_id_idx on public.notification (user_id, created_at desc);
create index if not exists notification_nao_lidas_idx on public.notification (user_id) where read_at is null;

alter table public.notification enable row level security;
