do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role' and typnamespace = 'public'::regnamespace) then
    create type public.user_role as enum ('TOURIST', 'GUIDE', 'EVENT_PROMOTER');
  end if;
  if not exists (select 1 from pg_type where typname = 'uf' and typnamespace = 'public'::regnamespace) then
    create type public.uf as enum (
      'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MS', 'MT', 'MG', 'PA',
      'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'tour_status' and typnamespace = 'public'::regnamespace) then
    create type public.tour_status as enum ('SCHEDULED', 'DONE', 'CANCELLED');
  end if;
  if not exists (select 1 from pg_type where typname = 'request_status' and typnamespace = 'public'::regnamespace) then
    create type public.request_status as enum ('PENDING', 'ACCEPTED', 'DENIED');
  end if;
end $$;

create table if not exists public."user" (
  user_id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  username text not null unique,
  email text not null unique,
  password text not null,
  phone text,
  cnpj text,
  role public.user_role,
  first_name text not null,
  last_name text not null,
  photo text not null
);

create table if not exists public.address (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  cep text not null check (cep ~ '^[0-9]{8}$'),
  uf public.uf not null,
  city text not null,
  neighborhood text not null,
  number text not null,
  street text not null,
  updated_at timestamptz,
  constraint unique_address_instance unique (cep, neighborhood, street, number)
);

create table if not exists public.tour (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by_id bigint not null references public."user" (user_id) on update cascade on delete restrict,
  title text not null,
  description text,
  price double precision not null,
  meeting_point text not null,
  estimated_duration_minutes bigint not null,
  address_id bigint references public.address (id) on update cascade on delete restrict,
  photo text
);

create table if not exists public.tour_instance (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tour_id bigint not null references public.tour (id) on update cascade on delete cascade,
  start_time timestamptz not null,
  max_capacity bigint not null,
  status public.tour_status not null
);

create table if not exists public.chat (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tour_instance_id bigint not null unique references public.tour_instance (id)
);

create table if not exists public.chat_message (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint not null references public."user" (user_id) on update cascade on delete restrict,
  chat_id bigint not null references public.chat (id) on update cascade on delete restrict,
  text text not null
);

create table if not exists public.tour_request (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tour_instance_id bigint not null references public.tour_instance (id) on update cascade on delete cascade,
  requester_id bigint not null,
  status public.request_status not null,
  last_update timestamptz,
  message text,
  last_message_read bigint references public.chat_message (id) on update cascade on delete restrict
);

alter table public."user" enable row level security;
alter table public.address enable row level security;
alter table public.tour enable row level security;
alter table public.tour_instance enable row level security;
alter table public.tour_request enable row level security;
alter table public.chat enable row level security;
alter table public.chat_message enable row level security;

do $$
begin
  if not exists (select 1 from pg_proc where proname = 'get_tour_members') then
    create function public.get_tour_members(tour_instance_id bigint)
    returns table (user_id bigint, first_name text, last_name text, photo text, role text)
    language sql stable as $body$
      select u.user_id, u.first_name, u.last_name, u.photo, u.role::text
      from public.tour_instance ti
      join public.tour t on t.id = ti.tour_id
      join public."user" u on u.user_id = t.created_by_id
      where ti.id = get_tour_members.tour_instance_id
      union
      select u.user_id, u.first_name, u.last_name, u.photo, u.role::text
      from public.tour_request tr
      join public."user" u on u.user_id = tr.requester_id
      where tr.tour_instance_id = get_tour_members.tour_instance_id and tr.status = 'ACCEPTED'
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_popular_tours') then
    create function public.get_popular_tours()
    returns table (id bigint, title text, photo text, guidephoto text, guide text, qt_turistas bigint)
    language sql stable as $body$
      select t.id, t.title, t.photo, u.photo, u.first_name, count(tr.id)
      from public.tour t
      join public."user" u on u.user_id = t.created_by_id
      left join public.tour_instance ti on ti.tour_id = t.id
      left join public.tour_request tr on tr.tour_instance_id = ti.id and tr.status = 'ACCEPTED'
      group by t.id, u.user_id
      order by count(tr.id) desc, t.created_at desc
      limit 20
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_tours_guide') then
    create function public.get_tours_guide(guide_id bigint)
    returns table (tour_id bigint, tour_instance_id bigint, tour_title text, tour_photo text, start_time timestamptz, chat_id bigint)
    language sql stable as $body$
      select t.id, ti.id, t.title, t.photo, ti.start_time, c.id
      from public.tour t
      join public.tour_instance ti on ti.tour_id = t.id
      left join public.chat c on c.tour_instance_id = ti.id
      where t.created_by_id = get_tours_guide.guide_id
        and exists (
          select 1 from public.tour_request tr
          where tr.tour_instance_id = ti.id and tr.status = 'ACCEPTED'
        )
      order by ti.start_time
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_tours_tourist') then
    create function public.get_tours_tourist(tourist_id bigint)
    returns table (tour_id bigint, tour_instance_id bigint, tour_title text, tour_photo text, start_time timestamptz, chat_id bigint)
    language sql stable as $body$
      select t.id, ti.id, t.title, t.photo, ti.start_time, c.id
      from public.tour_request tr
      join public.tour_instance ti on ti.id = tr.tour_instance_id
      join public.tour t on t.id = ti.tour_id
      left join public.chat c on c.tour_instance_id = ti.id
      where tr.requester_id = get_tours_tourist.tourist_id and tr.status = 'ACCEPTED'
      order by ti.start_time
    $body$;
  end if;

  if not exists (select 1 from pg_proc where proname = 'get_tour_by_chat') then
    create function public.get_tour_by_chat(chat_id bigint)
    returns table (tour_id bigint, tour_instance_id bigint, tour_title text, tour_photo text, start_time timestamptz)
    language sql stable as $body$
      select t.id, ti.id, t.title, t.photo, ti.start_time
      from public.chat c
      join public.tour_instance ti on ti.id = c.tour_instance_id
      join public.tour t on t.id = ti.tour_id
      where c.id = get_tour_by_chat.chat_id
    $body$;
  end if;
end $$;
