alter table public.tour
  add column if not exists photo_credit text;

create table if not exists public.tour_photo (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tour_id bigint not null references public.tour (id) on update cascade on delete cascade,
  url text not null,
  credit text,
  position integer not null default 0
);

create index if not exists tour_photo_tour_id_idx on public.tour_photo (tour_id, position);

alter table public.tour_photo enable row level security;
