create table if not exists public.tour_review (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tour_id bigint not null references public.tour (id) on update cascade on delete cascade,
  tour_instance_id bigint references public.tour_instance (id) on update cascade on delete set null,
  user_id bigint not null references public."user" (user_id) on update cascade on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text,
  constraint tour_review_uma_por_data unique (user_id, tour_instance_id)
);

create index if not exists tour_review_tour_id_idx on public.tour_review (tour_id, created_at desc);

alter table public.tour_review enable row level security;
